package gui;

import controllers.*;
import models.*;

import javax.swing.*;

public class LoginPage extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        setResizable(false);
        pack();
        setLocationRelativeTo(null); // middle of the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameText = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        showpasswordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setName("loginPage"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Welcome... Please Log in:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jlabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jlabel3.setText("Password:");
        getContentPane().add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 241, -1, -1));

        jlabel4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jlabel4.setText("User Name:");
        getContentPane().add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 173, -1, -1));

        loginButton.setBackground(new java.awt.Color(204, 204, 255));
        loginButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(this::loginButtonActionPerformed);
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 350, 165, 37));

        usernameText.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        usernameText.setText("moha");
        getContentPane().add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 170, 245, 33));

        passwordField.setText("12345");
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 240, 245, 33));

        showpasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showpasswordhandler(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                hidepasswordhandler(evt);
            }
        });
        showpasswordButton.addActionListener(this::showpasswordButtonActionPerformed);
        getContentPane().add(showpasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 301, 20, 20));

        jLabel2.setText("Show Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 303, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void messageDialog(String title, String message, int type) {
        JOptionPane.showMessageDialog(this,
                message,
                title,
                type);
    }
    private void showpasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordButtonActionPerformed

    private void showpasswordhandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpasswordhandler
        passwordField.setEchoChar((char) 0);
    }//GEN-LAST:event_showpasswordhandler

    private void hidepasswordhandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidepasswordhandler
        passwordField.setEchoChar('*');
    }//GEN-LAST:event_hidepasswordhandler

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameText.getText();
        String pass     = new String(passwordField.getPassword());
        username = username.trim();

        if (username.isEmpty() || pass.isEmpty()) {
            messageDialog("Empty Fields" , "Please enter both username and password.", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            SystemManager.getInstance().login(username, pass);

            messageDialog(
                    "Login Successful",
                    "Welcome Back " + SystemManager.getInstance().getCurrentUser().getName() + ".",
                    JOptionPane.INFORMATION_MESSAGE
            );

            this.dispose();
            new MainPage().setVisible(true);
        } catch (Exception e) {
            messageDialog("Login Failed", e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton showpasswordButton;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
