package gui;

import controllers.*;
import models.*;
import util.IdManager;

import javax.swing.*;
import java.awt.Cursor;
import java.time.LocalDateTime;

// mohannad: implementing card layout, explained here: https://docs.oracle.com/javase/tutorial/uiswing/layout/card.html
public class MainPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPage.class.getName());

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setResizable(false);
        pack();
        setLocationRelativeTo(null); // middle of the screen
        logoutLable.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Employee user = SystemManager.getInstance().getCurrentUser();
        welcomLable.setText(String.format("Welcome, %s (%s)", user.getName(), user.getRole().toString()));
        setupProfile();
    }

    void setupProfile() {
        Employee user = SystemManager.getInstance().getCurrentUser();
        if (user.getRole() == EmployeeRole.ADMIN) {
            usernamefield.setEditable(true);
            passwordfield.setEditable(true);
        }
        idfield.setText(Integer.toString(user.getId()));
        namefield.setText(user.getName());
        emailfield.setText(user.getEmail());
        phonefield.setText(user.getPhone());
        datefield.setText(user.getRegisterDate().split("T")[0]);
        rolefield.setText(user.getRole().toString());
        usernamefield.setText(user.getUserName());
        passwordfield.setText(user.getPassword());
    }
    
    void messageDialog(String title, String message, int type) {
        JOptionPane.showMessageDialog(this,
                    message,
                    title,
                    type);
    }
    
    void logOutUtil() {
        SystemManager.getInstance().logout();
        this.dispose();
        new LoginPage().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutLable = new javax.swing.JLabel();
        welcomLable = new javax.swing.JLabel();
        mainTappedPanel = new javax.swing.JTabbedPane();
        profilePanel = new javax.swing.JPanel();
        idfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phonefield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        datefield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rolefield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        updateButton = new javax.swing.JButton();
        addemp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        namefield1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        emailfield1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phonefield1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        usernamefield1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        passwordfield1 = new javax.swing.JPasswordField();
        addempButton = new javax.swing.JButton();
        roleselector = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        idsearch = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        usernamesearch = new javax.swing.JTextField();
        searchidButton = new javax.swing.JButton();
        searchusernameButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        resultname = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        resultemail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        resultphone = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        resultusername = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        resultpasswordfield2 = new javax.swing.JPasswordField();
        updatempButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        resultdatefield1 = new javax.swing.JTextField();
        resultrolefield1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Hyper Market System v1.0");
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                MainPageClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutLable.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        logoutLable.setForeground(new java.awt.Color(51, 51, 255));
        logoutLable.setText("<html><u>Log Out</u></html>");
        logoutLable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        logoutLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLableMouseClicked(evt);
            }
        });
        getContentPane().add(logoutLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1086, 18, -1, -1));

        welcomLable.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        welcomLable.setText("Welcome, ");
        getContentPane().add(welcomLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 18, -1, -1));

        mainTappedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainTappedPanel.setToolTipText("");
        mainTappedPanel.setName(""); // NOI18N

        profilePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profilePanel.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        profilePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idfield.setEditable(false);
        idfield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        idfield.setText("Id");
        idfield.setEnabled(false);
        idfield.setFocusCycleRoot(true);
        idfield.addActionListener(this::idfieldActionPerformed);
        profilePanel.add(idfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 300, -1));

        jLabel4.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel4.setText("Employee Id:");
        profilePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel5.setText("Name:");
        profilePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        namefield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        namefield.addActionListener(this::namefieldActionPerformed);
        profilePanel.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 300, -1));

        emailfield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        emailfield.addActionListener(this::emailfieldActionPerformed);
        profilePanel.add(emailfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 300, -1));

        jLabel6.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel6.setText("Email:");
        profilePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel7.setText("Phone:");
        profilePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        phonefield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        phonefield.addActionListener(this::phonefieldActionPerformed);
        profilePanel.add(phonefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 300, -1));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel8.setText("Register Date:");
        profilePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        datefield.setEditable(false);
        datefield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        datefield.addActionListener(this::datefieldActionPerformed);
        profilePanel.add(datefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 300, -1));

        jLabel9.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel9.setText("Role:");
        profilePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        rolefield.setEditable(false);
        rolefield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        rolefield.addActionListener(this::rolefieldActionPerformed);
        profilePanel.add(rolefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 300, -1));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel10.setText("Username:");
        profilePanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        usernamefield.setEditable(false);
        usernamefield.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        usernamefield.addActionListener(this::usernamefieldActionPerformed);
        profilePanel.add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 300, -1));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel11.setText("Password:");
        profilePanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        passwordfield.setEditable(false);
        profilePanel.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 300, 36));

        updateButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        updateButton.setText("Update Profile");
        updateButton.addActionListener(this::updateButtonActionPerformed);
        profilePanel.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 200, 50));

        mainTappedPanel.addTab("Profile", new javax.swing.ImageIcon(getClass().getResource("/gui/media/user.png")), profilePanel, ""); // NOI18N

        jLabel12.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel12.setText("Name:");

        namefield1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        namefield1.addActionListener(this::namefield1ActionPerformed);

        jLabel13.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel13.setText("Email:");

        emailfield1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        emailfield1.addActionListener(this::emailfield1ActionPerformed);

        jLabel14.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel14.setText("Phone:");

        phonefield1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        phonefield1.addActionListener(this::phonefield1ActionPerformed);

        jLabel15.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel15.setText("Role:");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel16.setText("Username:");

        usernamefield1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        usernamefield1.addActionListener(this::usernamefield1ActionPerformed);

        jLabel17.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel17.setText("Password:");

        addempButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        addempButton.setText("Add Employee");
        addempButton.addActionListener(this::addempButtonActionPerformed);

        roleselector.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        roleselector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "INVENTORY", "SALES", "MARKETER" }));

        javax.swing.GroupLayout addempLayout = new javax.swing.GroupLayout(addemp);
        addemp.setLayout(addempLayout);
        addempLayout.setHorizontalGroup(
            addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addempLayout.createSequentialGroup()
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addempLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addempLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(107, 107, 107)
                                .addComponent(namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addempLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(110, 110, 110)
                                .addComponent(emailfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addempLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(106, 106, 106)
                                .addComponent(phonefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addempLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(121, 121, 121)
                                .addComponent(roleselector, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addempLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(74, 74, 74)
                                .addComponent(usernamefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addempLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(79, 79, 79)
                                .addComponent(passwordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addempLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(addempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(598, 598, 598))
        );
        addempLayout.setVerticalGroup(
            addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addempLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(namefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(emailfield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(phonefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(roleselector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(usernamefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(passwordfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainTappedPanel.addTab("Add new employee", new javax.swing.ImageIcon(getClass().getResource("/gui/media/plus.png")), addemp); // NOI18N

        jLabel18.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel18.setText("Employee Id:");

        idsearch.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        idsearch.setFocusCycleRoot(true);
        idsearch.addActionListener(this::idsearchActionPerformed);

        jLabel19.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel19.setText("Username:");

        usernamesearch.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        usernamesearch.addActionListener(this::usernamesearchActionPerformed);

        searchidButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        searchidButton.setText("Search by ID");
        searchidButton.addActionListener(this::searchidButtonActionPerformed);

        searchusernameButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        searchusernameButton.setText("Search by Username");
        searchusernameButton.addActionListener(this::searchusernameButtonActionPerformed);

        jLabel20.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel20.setText("Name:");

        resultname.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        resultname.addActionListener(this::resultnameActionPerformed);

        jLabel21.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel21.setText("Email:");

        resultemail.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        resultemail.addActionListener(this::resultemailActionPerformed);

        jLabel22.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel22.setText("Phone:");

        resultphone.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        resultphone.addActionListener(this::resultphoneActionPerformed);

        jLabel23.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel23.setText("Username:");

        resultusername.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        resultusername.addActionListener(this::resultusernameActionPerformed);

        jLabel24.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel24.setText("Password:");

        updatempButton.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        updatempButton.setText("Update Employee");
        updatempButton.addActionListener(this::updatempButtonActionPerformed);

        jLabel25.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel25.setText("Register Date:");

        resultdatefield1.setEditable(false);
        resultdatefield1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        resultdatefield1.addActionListener(this::resultdatefield1ActionPerformed);

        resultrolefield1.setEditable(false);
        resultrolefield1.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        resultrolefield1.addActionListener(this::resultrolefield1ActionPerformed);

        jLabel26.setFont(new java.awt.Font("Noto Sans", 2, 18)); // NOI18N
        jLabel26.setText("Role:");

        resetButton.setText("Reset");
        resetButton.addActionListener(this::resetButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(49, 49, 49)
                        .addComponent(resultdatefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(searchidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchusernameButton))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(58, 58, 58)
                                    .addComponent(idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(74, 74, 74)
                                    .addComponent(usernamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(107, 107, 107)
                                .addComponent(resultname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(110, 110, 110)
                                .addComponent(resultemail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(106, 106, 106)
                                .addComponent(resultphone, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(74, 74, 74)
                                .addComponent(resultusername, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(79, 79, 79)
                                .addComponent(resultpasswordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(updatempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addGap(121, 121, 121)
                        .addComponent(resultrolefield1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(resultname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(resultemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(resultphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(resultdatefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(resetButton))
                            .addComponent(resultrolefield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(resultusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(resultpasswordfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(updatempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(usernamesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchidButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchusernameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        mainTappedPanel.addTab("Search & Update Employees", new javax.swing.ImageIcon(getClass().getResource("/gui/media/magnifying-glass.png")), jPanel1); // NOI18N

        getContentPane().add(mainTappedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1140, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void logoutLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLableMouseClicked
        this.logOutUtil();
    }//GEN-LAST:event_logoutLableMouseClicked

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void rolefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rolefieldActionPerformed

    private void datefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefieldActionPerformed

    private void phonefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefieldActionPerformed

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void idfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idfieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Employee user = SystemManager.getInstance().getCurrentUser();
        String username = usernamefield.getText();
        String pass     = new String(passwordfield.getPassword());
        String newName  = namefield.getText();
        String newEmail = emailfield.getText();
        String newPhone = phonefield.getText();

        // only admin can change username and password
        if (user.getRole() != EmployeeRole.ADMIN) {
            username = user.getUserName();
            pass = user.getPassword();
        }

        if (username.isEmpty() || pass.isEmpty() || newName.isEmpty() || newEmail.isEmpty() || newPhone.isEmpty()) {
            messageDialog("Empty Fields" , "Please fill any empty fields.", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Employee newDate = new Employee(
                user.getId(),
                newName,
                newEmail,
                newPhone,
                username,
                pass,
                user.getRegisterDate(),
                user.getRole().toString()
        );

        int opt = javax.swing.JOptionPane.showConfirmDialog(this,
                "You'll be logged out from this session.",
                "Logout Notice",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (opt == JOptionPane.YES_OPTION) {
            try {
                SystemManager.getInstance().updateEmployee(user.getId(), newDate);
                logOutUtil();
            } catch (Exception e) {
                messageDialog("Something Wrong!", "Error: " + e.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void namefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefield1ActionPerformed

    private void emailfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfield1ActionPerformed

    private void phonefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phonefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phonefield1ActionPerformed

    private void usernamefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefield1ActionPerformed

    private void addempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addempButtonActionPerformed
        Employee user = SystemManager.getInstance().getCurrentUser();
        if (user.getRole() != EmployeeRole.ADMIN)
            return;
        String username = usernamefield1.getText();
        String pass     = new String(passwordfield1.getPassword());
        String newName  = namefield1.getText();
        String newEmail = emailfield1.getText();
        String newPhone = phonefield1.getText();
        String newRole  = roleselector.getSelectedItem().toString();

        if (username.isEmpty() || pass.isEmpty() || newName.isEmpty() || newEmail.isEmpty() || newPhone.isEmpty() || newRole.isEmpty()) {
            messageDialog("Empty Fields" , "Please fill any empty fields.", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Employee newDate = new Employee(
                IdManager.nextId(),
                newName,
                newEmail,
                newPhone,
                username,
                pass,
                LocalDateTime.now().toString(),
                newRole
        );

        try {
            SystemManager.getInstance().addEmployee(newDate);
            messageDialog("Success!", String.format("Employee added with id %d.", newDate.getId()), JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            messageDialog("Something Wrong!", "Error: " + e.getMessage(), JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addempButtonActionPerformed

    private void MainPageClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_MainPageClosing
        int opt = JOptionPane.showConfirmDialog(
                this,
                "Are you sure to Exit? There may be unsaved data!",
                "Exit?",
                JOptionPane.YES_NO_OPTION
        );

        if (opt == JOptionPane.YES_OPTION) {
            SystemManager.getInstance().logout();
            this.dispose();
        }
    }//GEN-LAST:event_MainPageClosing

    private void idsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idsearchActionPerformed

    private void usernamesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamesearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamesearchActionPerformed

    private Employee resultUser;

    private void resetSearchResult() {
        resultUser = null;
        resultemail.setText("");
        resultusername.setText("");
        resultname.setText("");
        resultphone.setText("");
        resultpasswordfield2.setText("");
        resultdatefield1.setText("");
        resultrolefield1.setText("");
    }

    private void showSearchResult(Employee emp) {
        messageDialog("Success!", "User found!", JOptionPane.INFORMATION_MESSAGE);
        resultemail.setText(emp.getEmail());
        resultusername.setText(emp.getUserName());
        resultname.setText(emp.getName());
        resultphone.setText(emp.getPhone());
        resultpasswordfield2.setText(emp.getPassword());
        resultdatefield1.setText(emp.getRegisterDate().split("T")[0]);
        resultrolefield1.setText(emp.getRole().toString());
        resultUser = emp;
    }

    private void searchidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchidButtonActionPerformed
        resetSearchResult();

        int id;

        try {
            id = Integer.parseInt(idsearch.getText());
        } catch (Exception e) {
            messageDialog("Something Wrong!", "Error: Please enter a valid Id.", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Employee emp = SystemManager.getInstance().searchEmployeeById(id);
        if (emp == null) {
            messageDialog("Something Wrong!", String.format("Error: No employee with Id %d.", id), JOptionPane.ERROR_MESSAGE);
            return;
        }

        showSearchResult(emp);
    }//GEN-LAST:event_searchidButtonActionPerformed

    private void searchusernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchusernameButtonActionPerformed
        resetSearchResult();
        String username = usernamesearch.getText();
        username = username.trim();

        if (username.isEmpty()) {
            messageDialog("Something Wrong!", "Please enter a username.", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Employee emp = SystemManager.getInstance().searchEmployeeByUsername(username);
        if (emp == null) {
            messageDialog("Something Wrong!", String.format("Error: No employee with username (%s).", username), JOptionPane.ERROR_MESSAGE);
            return;
        }

        showSearchResult(emp);
    }//GEN-LAST:event_searchusernameButtonActionPerformed

    private void resultnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultnameActionPerformed

    private void resultemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultemailActionPerformed

    private void resultphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultphoneActionPerformed

    private void resultusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultusernameActionPerformed

    private void updatempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatempButtonActionPerformed
        Employee currentUser = SystemManager.getInstance().getCurrentUser();
        if (resultUser == null) {
            messageDialog("Something Wrong!", "Please search for a user first.", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (currentUser.getId() == resultUser.getId()) {
            messageDialog("Something Wrong!", "Please, Use Profile tab instead.", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String username = resultusername.getText();
        String pass     = new String(resultpasswordfield2.getPassword());
        String newName  = resultname.getText();
        String newEmail = resultemail.getText();
        String newPhone = resultphone.getText();

        if (username.isEmpty() || pass.isEmpty() || newName.isEmpty() || newEmail.isEmpty() || newPhone.isEmpty()) {
            messageDialog("Empty Fields" , "Please fill any empty fields to update.", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Employee newDate = new Employee(
                resultUser.getId(),
                newName,
                newEmail,
                newPhone,
                username,
                pass,
                resultUser.getRegisterDate(),
                resultUser.getRole().toString()
        );

        int opt = javax.swing.JOptionPane.showConfirmDialog(this,
                "Confirm updating? Operation cannot be reverted.",
                "Update Notice",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (opt == JOptionPane.YES_OPTION) {
            try {
                SystemManager.getInstance().updateEmployee(resultUser.getId(), newDate);
                messageDialog("Success!", "Employee updated successfully", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                messageDialog("Something Wrong!", "Error: " + e.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_updatempButtonActionPerformed

    private void resultdatefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultdatefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultdatefield1ActionPerformed

    private void resultrolefield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultrolefield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultrolefield1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        resetSearchResult();
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addemp;
    private javax.swing.JButton addempButton;
    private javax.swing.JTextField datefield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JTextField emailfield1;
    private javax.swing.JTextField idfield;
    private javax.swing.JTextField idsearch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutLable;
    private javax.swing.JTabbedPane mainTappedPanel;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField namefield1;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JPasswordField passwordfield1;
    private javax.swing.JTextField phonefield;
    private javax.swing.JTextField phonefield1;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField resultdatefield1;
    private javax.swing.JTextField resultemail;
    private javax.swing.JTextField resultname;
    private javax.swing.JPasswordField resultpasswordfield2;
    private javax.swing.JTextField resultphone;
    private javax.swing.JTextField resultrolefield1;
    private javax.swing.JTextField resultusername;
    private javax.swing.JTextField rolefield;
    private javax.swing.JComboBox<String> roleselector;
    private javax.swing.JButton searchidButton;
    private javax.swing.JButton searchusernameButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updatempButton;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JTextField usernamefield1;
    private javax.swing.JTextField usernamesearch;
    private javax.swing.JLabel welcomLable;
    // End of variables declaration//GEN-END:variables
}
